version: '3.4'

services:
  mssql_server:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce

  showroom.api:
    image: ${DOCKER_REGISTRY-}showroomapi
    build:
      context: .
      dockerfile: Services/Showroom/Showroom.Api/Dockerfile

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  sqlserver_data:
  data: